### ISSUE TITLE
Solving game with different columns and rows

### ISSUE THREAD

**Issue by jdleung** [MilanPecov/15-Puzzle-Solvers#5]
Tested two simple puzzles, ignored checking `isSolvable`, and it seems that the solver can handle puzzles with different columns and rows, but the solver limits same columns and rows. Does it cause problem on complex puzzles?

**Comment by MilanPecov** [comment]
Yes, it's just the `Puzzle.is_solvable` that requires modification to handle non-square puzzles. Feel free to submit a PR, or I can address this when I have time

**Comment by jdleung** [comment]
I tried to integrate a solver in the game, but I found that levels larger than 4x4 can need a lot of time to solve, especially solved with A*, maybe it's not good idea to doing so. :-(

**Comment by MilanPecov** [comment]
Thanks for sharing your experience with integrating the solver. For larger puzzle it's indeed challenging due to the increased search space complexity. You might find it helpful to track the solver's performance as outlined in the Readme. Here's a quick example:

```
algorithm = AStar(puzzle, heuristic='manhattan_distance') # default heuristic
puzzle_solver = PuzzleSolver(algorithm)  
puzzle_solver.run()
puzzle_solver.print_performance() 
```

This approach helps in understanding how the algorithm's efficiency varies with the complexity of the search space and the number of nodes it needs to explore to find the solution.

Hope this helps!

**Comment by jdleung** [comment]
It's probably not a good idea to Integrate an instant solver in the game, but it did helps in understanding the algorithm. I'll try the the example later, hope to dig deeper. Thanks for your sharing.
